'use client';

import { useState } from 'react';
import {
  ALL_QUESTIONS_PROMPT,
  DEMO_QUESTIONS,
  RECORDED_RUNS,
} from '../fixtures/demo-questions';
import { DOWNLOAD_FILENAME } from '../fixtures/demo-timeline';

function CopyButton({ text, label }: { text: string; label: string }) {
  // Clipboard access can be denied outright (permissions, insecure context,
  // some embedded browsers). Failing silently would leave the button looking
  // broken, so a refusal falls back to something the reviewer can still act on.
  const [state, setState] = useState<'idle' | 'ok' | 'fail'>('idle');
  return (
    <button
      className="primary"
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(text);
          setState('ok');
        } catch {
          setState('fail');
        }
        window.setTimeout(() => setState('idle'), 2400);
      }}
    >
      <span aria-live="polite">
        {state === 'ok' ? 'Copied' : state === 'fail' ? 'Copy blocked — select them below' : label}
      </span>
    </button>
  );
}

/**
 * The before-state, generated by the reviewer rather than asserted by me.
 *
 * The honest version of a comparison is one where the other side isn't
 * written by the person making the claim. So: download the file, upload it to
 * whichever AI you already trust, ask four questions, then come back.
 */
export function TryItYourself() {
  return (
    <section className="panel step">
      <div className="steptag">First — watch it happen</div>
      <h2 className="big">Take two minutes and break your own AI</h2>
      <p className="lead">
        Download this project log and upload it to ChatGPT, Claude, Gemini —
        whichever you already use. Ask it the four questions below. Then come
        back and ask the same four here.
      </p>

      <div className="row tail">
        <a className="btnlink primary" href={`/${DOWNLOAD_FILENAME}`} download>
          Download the project log
        </a>
        <CopyButton text={ALL_QUESTIONS_PROMPT} label="Copy all four questions" />
      </div>

      <ol className="qsteps">
        {DEMO_QUESTIONS.map((q) => (
          <li key={q.id}>
            <p className="qtext">{q.question}</p>
            <p className="dim small flush">{q.watchFor}</p>
          </li>
        ))}
      </ol>

      <div className="notice">
        <strong>Being straight with you:</strong> some models will get some of
        these right. That is not the problem. The problem is that a right answer
        and a wrong one arrive looking exactly the same — fluent, sourced,
        confident. Nothing in the reply tells you which ones are safe to act on.
        That is the gap this fills.
      </div>

      <details>
        <summary>
          What happened when I ran it — three models, {RECORDED_RUNS.date}
        </summary>
        <p className="dim small">
          Same file, same four questions, no retries and no prompt tuning. Not a
          benchmark — three conversations, kept because a real result beats an
          assertion. The pattern matters more than the tally.
        </p>

        <div className="tablewrap">
          <table className="runtable">
            <thead>
              <tr>
                <th>Question</th>
                {RECORDED_RUNS.models.map((m) => (
                  <th key={m}>{m}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {RECORDED_RUNS.rows.map((row) => {
                const q = DEMO_QUESTIONS.find((x) => x.id === row.id);
                return (
                  <tr key={row.id}>
                    <td>
                      <span className="qshort">{q?.label}</span>
                      <span className={`chip verdict-${row.verdict}`}>{row.verdict}</span>
                    </td>
                    {row.results.map((r, i) => (
                      <td key={i}>
                        <span className={`chip run-${r.outcome}`}>{r.outcome}</span>
                        <p className="dim small tail">{r.what}</p>
                      </td>
                    ))}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>

        <p className="dim">
          <strong>Two of these are solved.</strong> Asking what was true on a
          past date, and admitting a number was never recorded — every model got
          both right, every time. Canon claims no credit there.
        </p>
        <p className="dim">
          <strong>The stale premise is closing.</strong> A year ago this failed
          outright; now the strongest model catches both halves before answering.
          Note what the middle column did though: it fixed the date and still
          addressed the message to the person who left. Half a premise caught is
          a sent message that goes to the wrong desk.
        </p>
        <p className="dim flush">
          <strong>The contradiction is not solved.</strong> Two models picked a
          winner from two entries dated the same day and never mentioned the one
          they discarded. The third disclosed the conflict and then leaned
          anyway. Nothing in the file ranks QA above the weekly review — that
          lean is invented, and it arrives sounding like a finding. This is the
          case that does not get better with a bigger model, because it is not a
          knowledge problem. It is a question about what the evidence licenses.
        </p>
      </details>
    </section>
  );
}
