'use client';

import { useState } from 'react';
import { ALL_QUESTIONS_PROMPT, DEMO_QUESTIONS } from '../fixtures/demo-questions';
import { DOWNLOAD_FILENAME } from '../fixtures/demo-timeline';

function CopyButton({ text, label }: { text: string; label: string }) {
  // Clipboard access can be denied outright (permissions, insecure context,
  // some embedded browsers). Failing silently would leave the button looking
  // broken, so a refusal falls back to something the reviewer can still act on.
  const [state, setState] = useState<'idle' | 'ok' | 'fail'>('idle');
  return (
    <button
      className="primary"
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(text);
          setState('ok');
        } catch {
          setState('fail');
        }
        window.setTimeout(() => setState('idle'), 2400);
      }}
    >
      {state === 'ok' ? 'Copied' : state === 'fail' ? 'Copy blocked — select them below' : label}
    </button>
  );
}

/**
 * The before-state, generated by the reviewer rather than asserted by me.
 *
 * The honest version of a comparison is one where the other side isn't
 * written by the person making the claim. So: download the file, upload it to
 * whichever AI you already trust, ask four questions, then come back.
 */
export function TryItYourself() {
  return (
    <section className="panel step">
      <div className="steptag">First — watch it happen</div>
      <h2 className="big">Take two minutes and break your own AI</h2>
      <p className="lead">
        Download this project log and upload it to ChatGPT, Claude, Gemini —
        whichever you already use. Ask it the four questions below. Then come
        back and ask the same four here.
      </p>

      <div className="row tail">
        <a className="btnlink primary" href={`/${DOWNLOAD_FILENAME}`} download>
          Download the project log
        </a>
        <CopyButton text={ALL_QUESTIONS_PROMPT} label="Copy all four questions" />
      </div>

      <ol className="qsteps">
        {DEMO_QUESTIONS.map((q) => (
          <li key={q.id}>
            <p className="qtext">{q.question}</p>
            <p className="dim small flush">{q.watchFor}</p>
          </li>
        ))}
      </ol>

      <div className="notice">
        <strong>Being straight with you:</strong> some models will get some of
        these right. That is not the problem. The problem is that a right answer
        and a wrong one arrive looking exactly the same — fluent, sourced,
        confident. Nothing in the reply tells you which ones are safe to act on.
        That is the gap this fills.
      </div>
    </section>
  );
}
