'use client';

import { useState } from 'react';
import {
  ALL_QUESTIONS_PROMPT,
  DEMO_QUESTIONS,
  RECORDED_RUN,
} from '../fixtures/demo-questions';
import { DOWNLOAD_FILENAME } from '../fixtures/demo-timeline';

function CopyButton({ text, label }: { text: string; label: string }) {
  // Clipboard access can be denied outright (permissions, insecure context,
  // some embedded browsers). Failing silently would leave the button looking
  // broken, so a refusal falls back to something the reviewer can still act on.
  const [state, setState] = useState<'idle' | 'ok' | 'fail'>('idle');
  return (
    <button
      className="primary"
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(text);
          setState('ok');
        } catch {
          setState('fail');
        }
        window.setTimeout(() => setState('idle'), 2400);
      }}
    >
      <span aria-live="polite">
        {state === 'ok' ? 'Copied' : state === 'fail' ? 'Copy blocked — select them below' : label}
      </span>
    </button>
  );
}

/**
 * The before-state, generated by the reviewer rather than asserted by me.
 *
 * The honest version of a comparison is one where the other side isn't
 * written by the person making the claim. So: download the file, upload it to
 * whichever AI you already trust, ask four questions, then come back.
 */
export function TryItYourself() {
  return (
    <section className="panel step">
      <div className="steptag">First — watch it happen</div>
      <h2 className="big">Take two minutes and break your own AI</h2>
      <p className="lead">
        Download this project log and upload it to ChatGPT, Claude, Gemini —
        whichever you already use. Ask it the four questions below. Then come
        back and ask the same four here.
      </p>

      <div className="row tail">
        <a className="btnlink primary" href={`/${DOWNLOAD_FILENAME}`} download>
          Download the project log
        </a>
        <CopyButton text={ALL_QUESTIONS_PROMPT} label="Copy all four questions" />
      </div>

      <ol className="qsteps">
        {DEMO_QUESTIONS.map((q) => (
          <li key={q.id}>
            <p className="qtext">{q.question}</p>
            <p className="dim small flush">{q.watchFor}</p>
          </li>
        ))}
      </ol>

      <div className="notice">
        <strong>Being straight with you:</strong> some models will get some of
        these right. That is not the problem. The problem is that a right answer
        and a wrong one arrive looking exactly the same — fluent, sourced,
        confident. Nothing in the reply tells you which ones are safe to act on.
        That is the gap this fills.
      </div>

      <details>
        <summary>
          What happened when I ran it — {RECORDED_RUN.model}, {RECORDED_RUN.date}
        </summary>
        <p className="dim small">
          One conversation, one model, one day. Not a benchmark, and not a
          claim about models in general — kept because a real result is worth
          more than an assertion. Two of four right, one wrong, one that knew
          the answer and did the wrong thing anyway.
        </p>
        <ol className="runlist">
          {RECORDED_RUN.results.map((r) => {
            const q = DEMO_QUESTIONS.find((x) => x.id === r.id);
            return (
              <li key={r.id}>
                <span className={`chip run-${r.outcome}`}>
                  {r.outcome === 'right'
                    ? 'got it'
                    : r.outcome === 'wrong'
                      ? 'got it wrong'
                      : 'knew, still did it'}
                </span>{' '}
                <span className="mono small">{q?.question}</span>
                <p className="dim small tail">{r.what}</p>
              </li>
            );
          })}
        </ol>
        <p className="dim flush">
          The first one is the one worth sitting with. The model had the right
          answer and put it <em>below</em> the draft, as prose. A person reading
          the whole reply catches it. An agent handed &ldquo;draft this
          message&rdquo; takes the message. A verdict is machine-readable; a
          caveat is not.
        </p>
      </details>
    </section>
  );
}
